### ISSUE TITLE
Crash on API16 for titles containing % character

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-Editor-Android#465]
I am guessing the following crash happens due to the deprecated methods getting called with the new parameter. I don't think this should normally happen, but it's still a good idea to update the deprecated methods.

/cc @aforcier because I don't know who works on this editor anymore.

```
Fatal Exception: java.lang.IllegalArgumentException: Invalid % sequence at 187: callback-response-string:function=getHTMLForCallback~id=zss_field_title~contents=Ripped-off Britons: Democracy puts strength in the hands of the many. Why in democratic Britain are the 90% treated like cattle for milking and for eating?
       at libcore.net.UriCodec.decode(UriCodec.java:169)
       at java.net.URLDecoder.decode(URLDecoder.java:45)
       at org.wordpress.android.editor.EditorWebViewAbstract$1.shouldOverrideUrlLoading(EditorWebViewAbstract.java:64)
       at android.webkit.CallbackProxy.uiOverrideUrlLoading(CallbackProxy.java:341)
       at android.webkit.CallbackProxy.handleMessage(CallbackProxy.java:466)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4963)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by aforcier** [comment]
I don't think the deprecated methods are the cause - from the crash reports, this is only happening on API 16. It looks like an HTML encoding issue.
